---
#play book para la instalacion de wordpress 
#configuracion del mismo, también la configuracion
#de nginx
- hosts: all
#varibles a usar
  vars:
    local_root: files/
#tareas para usar en esta provision
  tasks:
# instalamos java para ejecutar jenkins
  - name: intall JDK-MAVEN-UNZIP
    apt: 
      name: "{{packages}}" 
      state: present
    vars:
      packages:
      - default-jdk
      - maven
      - docker.io
      - unzip
    become: true
  - name: Download terraform.zip
    get_url:
      url: https://releases.hashicorp.com/terraform/0.12.24/terraform_0.12.24_linux_amd64.zip
      dest: /home/ubuntu/
  - name: Execute the command in remote
    shell: unzip /home/ubuntu/terraform_0.12.24_linux_amd64.zip && mv /home/ubuntu/terraform /usr/local/bin/
    become: yes
#jenkins setings - no esta en github porque pesa 500mb - a adjuntar
  - name: setting config jenkins
    copy:
      src: "{{local_root}}jenkins.zip"
      dest: /home/ubuntu/jenkins.zip
      mode: 0777
    become: yes
  - name: unzip  jenkins config
    shell: unzip /home/ubuntu/jenkins.zip && chmod -R  777 /home/ubuntu/.jenkins
    become: yes
#tenemos que tener variables.tfvars, archivo con credenciales no subido. 
  - name: credentials terraform
    copy:
      src: "{{local_root}}/variables.tfvars"
      dest: "/home/ubuntu/variables.tfvars"
      mode: 0777
#Copiamos la ejecución de jenkins
  - name: Jenkins jar
    copy:
      src: "{{local_root}}jen.service"
      dest: /etc/systemd/system/
    become: true
#iniciamos el servicio de Jenkins
  - name: archivo de ejecucion de servicio 
    copy:
      src: "{{local_root}}jenkinsService"
      dest: /home/ubuntu/
      mode: 0777
    become: true
  - name: download jenkins
    get_url:
      url: http://mirrors.jenkins.io/war/latest/jenkins.war
      dest: /home/ubuntu/jenkins.war
      mode: 0777
  - name: Execute enable  service
    become: yes
    shell: systemctl enable jen
  - name: credentials AWS
    copy:
      src:  "{{local_root}}/.aws"
      dest: /home/ubuntu/
      mode: 0777